# Generated by Django 4.2 on 2023-05-05 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_entities_defence_entities_health_entities_stamina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='appearted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entities',
            name='appearted_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entities',
            name='disappearted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entities',
            name='disappearted_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
