# Generated by Django 4.2 on 2023-05-05 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_alter_pokemon_next_evolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='appearted_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата явления'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='appearted_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время явления'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='defence',
            field=models.IntegerField(default=100, verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='disappearted_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата исчезновения'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='disappearted_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время исчезновения'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='health',
            field=models.IntegerField(default=100, verbose_name='Здоровье'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Координата-широта'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Координата-долгота'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Имя Покемона'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='stamina',
            field=models.IntegerField(default=100, verbose_name='Выносливость'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='strength',
            field=models.IntegerField(default=100, verbose_name='Сила'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='pokemons', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution_set', to='pokemon_entities.pokemon', verbose_name='Эволюционирует из'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_evolution_set', to='pokemon_entities.pokemon', verbose_name='Эволюционировал в'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя(на английском)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя(на японском)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
