# Generated by Django 4.2 on 2023-05-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_alter_entities_appearted_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entities',
            name='appearted_date',
        ),
        migrations.RemoveField(
            model_name='entities',
            name='appearted_time',
        ),
        migrations.RemoveField(
            model_name='entities',
            name='disappearted_date',
        ),
        migrations.RemoveField(
            model_name='entities',
            name='disappearted_time',
        ),
        migrations.AddField(
            model_name='entities',
            name='appearted_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Момент явления'),
        ),
        migrations.AddField(
            model_name='entities',
            name='disappearted_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Момент исчезновения'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='defence',
            field=models.IntegerField(verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='health',
            field=models.IntegerField(verbose_name='Здоровье'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='level',
            field=models.IntegerField(verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entities', to='pokemon_entities.pokemon', verbose_name='Имя Покемона'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='stamina',
            field=models.IntegerField(verbose_name='Выносливость'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='strength',
            field=models.IntegerField(verbose_name='Сила'),
        ),
    ]
